theme: readthedocs
site_name: py2cytoscape
pages:
  - Home: index.md
  - cyrest:
    - Intro: cyrest/index.md
    - Commands: cyrest/commands.md
    - command: cyrest/command.md
    - cybrowser: cyrest/cybrowser.md
    - session: cyrest/session.md
